services:
  otel-collector:
    image: otel/opentelemetry-collector:0.102.1
    # image: otel/opentelemetry-collector-contrib:0.102.1
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - source: ./etc/otel-collector-config.yaml
        target: /etc/otel-collector-config.yaml
        type: bind
        read_only: true
    ports:
      - 4317:4317 # OTLP over gRPC
      - 4318:4318 # OTLP over HTTP
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 55679:55679
