services:
  proxy:
    build:
      context: .
      target: final
    ports:
      - 8080:8080

  otel-collector:
    image: otel/opentelemetry-collector:0.102.1
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - source: ./otel/otel-collector-config.yaml
        target: /etc/otel-collector-config.yaml
        type: bind
        read_only: true
    ports:
      - 4317:4317 # OTLP over gRPC
      - 4318:4318 # OTLP over HTTP
